services:
  learningcsharp:
    image: learningcsharp
    build:
      context: .
      dockerfile: LearningCSharp/Dockerfile

  learningminimalapi:
    image: learningminimalapi
    build:
      context: .
      dockerfile: LearningMinimalAPI/Dockerfile

  learningauth:
    image: learningauth
    build:
      context: .
      dockerfile: LearningAuth/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  learningcontrollers:
    image: learningcontrollers
    build:
      context: .
      dockerfile: LearningControllers/Dockerfile

