CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Value" text,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "FirstName" text,
    "LastName" text,
    "Email" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "WorkItemStates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Value" character varying(50) NOT NULL,
    CONSTRAINT "PK_WorkItemStates" PRIMARY KEY ("Id")
);

CREATE TABLE "Addresses" (
    "Id" uuid NOT NULL,
    "Country" text,
    "City" text,
    "Street" text,
    "PostalCode" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StateId" integer NOT NULL,
    "Area" varchar(200),
    "Iteration_Path" text,
    "Priority" integer NOT NULL DEFAULT 1,
    "AuthorId" uuid NOT NULL,
    "Discriminator" character varying(8) NOT NULL,
    "StartDate" timestamp with time zone,
    "EndDate" timestamp(3) with time zone,
    "Efford" numeric(5,2),
    "Activity" character varying(200),
    "RemainingWork" numeric(14,2),
    CONSTRAINT "PK_WorkItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkItems_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkItems_WorkItemStates_StateId" FOREIGN KEY ("StateId") REFERENCES "WorkItemStates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Message" text,
    "Author" text,
    "CreatedTime" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedTime" timestamp with time zone,
    "WorkItemId" integer NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_WorkItems_WorkItemId" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkItemTag" (
    "WorkItemId" integer NOT NULL,
    "TagId" integer NOT NULL,
    "PublicationDate" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_WorkItemTag" PRIMARY KEY ("TagId", "WorkItemId"),
    CONSTRAINT "FK_WorkItemTag_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkItemTag_WorkItems_WorkItemId" FOREIGN KEY ("WorkItemId") REFERENCES "WorkItems" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");

CREATE INDEX "IX_Comments_WorkItemId" ON "Comments" ("WorkItemId");

CREATE INDEX "IX_WorkItems_AuthorId" ON "WorkItems" ("AuthorId");

CREATE INDEX "IX_WorkItems_StateId" ON "WorkItems" ("StateId");

CREATE INDEX "IX_WorkItemTag_WorkItemId" ON "WorkItemTag" ("WorkItemId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250512114517_Init', '8.0.15');

COMMIT;

START TRANSACTION;

ALTER TABLE "WorkItemStates" ALTER COLUMN "Value" TYPE character varying(60);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250512115547_StateValueLength', '8.0.15');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" ADD "FullName" text;


                UPDATE public."Users"
                SET "FullName" = "FirstName" || ' ' || "LastName"
            

ALTER TABLE "Users" DROP COLUMN "FirstName";

ALTER TABLE "Users" DROP COLUMN "LastName";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250512120123_UserFullName', '8.0.15');

COMMIT;

