@host = http://localhost:5264

GET {{host}}/tags/
Accept: application/json

###
GET {{host}}/firstEpicFirstUserOne

###
GET {{host}}/toDoWorkItems


###
GET {{host}}/newComments


###
GET {{host}}/epicOnHold


###
GET {{host}}/authorWithMostComment


###
PUT {{host}}/updateAreaPriority


###
PUT {{host}}/updateState


###
POST {{host}}/createTag


###
DELETE {{host}}/deleteTag


###
GET {{host}}/getUserComments


###
GET {{host}}/getRawSql


###
GET {{host}}/getDataFromView