@host = http://localhost:5264

GET {{host}}/tags/
Accept: application/json

###
GET {{host}}/firstEpicFirstUserOne

###
GET {{host}}/toDoWorkItems


###
GET {{host}}/newComments


###
GET {{host}}/epicOnHold


###
GET {{host}}/authorWithMostComment