@HOST=http://localhost:5266/

###
GET {{HOST}}/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Impkb2JyIiwic3ViIjoiamRvYnIiLCJqdGkiOiI1MTY3M2M0NyIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQ5NjkiLCJodHRwczovL2xvY2FsaG9zdDo0NDM1OSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI2NiIsImh0dHBzOi8vbG9jYWxob3N0OjcxNzEiXSwibmJmIjoxNzQ2MTczODUyLCJleHAiOjE3NTQxMjI2NTIsImlhdCI6MTc0NjE3Mzg1MywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.ILVaVijEmiYpkomA7y6aGXxSCvwb12o0CrYaklYOuso