@HOST=http://localhost:5266/

###
GET {{HOST}}/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Impkb2JyIiwic3ViIjoiamRvYnIiLCJqdGkiOiI1MTY3M2M0NyIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQ5NjkiLCJodHRwczovL2xvY2FsaG9zdDo0NDM1OSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI2NiIsImh0dHBzOi8vbG9jYWxob3N0OjcxNzEiXSwibmJmIjoxNzQ2MTczODUyLCJleHAiOjE3NTQxMjI2NTIsImlhdCI6MTc0NjE3Mzg1MywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.ILVaVijEmiYpkomA7y6aGXxSCvwb12o0CrYaklYOuso


###
GET {{HOST}}/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Impkb2JyIiwic3ViIjoiamRvYnIiLCJqdGkiOiJjOGI5ODg1YiIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQ5NjkiLCJodHRwczovL2xvY2FsaG9zdDo0NDM1OSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI2NiIsImh0dHBzOi8vbG9jYWxob3N0OjcxNzEiXSwibmJmIjoxNzQ2MTc0NTE0LCJleHAiOjE3NTQxMjMzMTQsImlhdCI6MTc0NjE3NDUxNSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.4ERcxA3NpKA5zkSJ_XgrDYWFtZ0nhXrBs08HgfY3_LQ


###
GET {{HOST}}/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Impkb2JyIiwic3ViIjoiamRvYnIiLCJqdGkiOiI4NzA4ODNmNiIsInJvbGUiOiJwbGF5ZXIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0OTY5IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTkiLCJodHRwOi8vbG9jYWxob3N0OjUyNjYiLCJodHRwczovL2xvY2FsaG9zdDo3MTcxIl0sIm5iZiI6MTc0NjE3NTE3MywiZXhwIjoxNzU0MTIzOTczLCJpYXQiOjE3NDYxNzUxNzQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.yAHIlXAqLP29VvI87ptEI-TEDmu2ClLxrX0Q7mCBh1k


###
GET {{HOST}}/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiNGY0Y2FlOTciLCJyb2xlIjoicGxheWVyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDk2OSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzU5IiwiaHR0cDovL2xvY2FsaG9zdDo1MjY2IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE3MSJdLCJuYmYiOjE3NDYxNzU0MTEsImV4cCI6MTc1NDEyNDIxMSwiaWF0IjoxNzQ2MTc1NDEyLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.Uqg3tPWhsksoOQ7m9wb04_7CeA5aVK1eEoD_HSJs5xA


###
GET {{HOST}}/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjIiLCJzdWIiOiJwbGF5ZXIyIiwianRpIjoiNTA2ZjY5MmYiLCJyb2xlIjoicGxheWVyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDk2OSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzU5IiwiaHR0cDovL2xvY2FsaG9zdDo1MjY2IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE3MSJdLCJuYmYiOjE3NDYxNzU1MjUsImV4cCI6MTc1NDEyNDMyNSwiaWF0IjoxNzQ2MTc1NTI2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.B_XrcXopH52O6pDA--UV7IMp7kqR-cGHQZCe3Ma_wHs


###
GET {{HOST}}/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiMzBjMTllZDgiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQ5NjkiLCJodHRwczovL2xvY2FsaG9zdDo0NDM1OSIsImh0dHA6Ly9sb2NhbGhvc3Q6NTI2NiIsImh0dHBzOi8vbG9jYWxob3N0OjcxNzEiXSwibmJmIjoxNzQ2MTc1ODE0LCJleHAiOjE3NTQxMjQ2MTQsImlhdCI6MTc0NjE3NTgxNiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.WBNdFOnuy1sse2GeNJGhGaQ7L0MyQDqcg7SIHJqaIvA