@HostAddress = http://localhost:5067

GET {{HostAddress}}/
Accept: application/json

###
GET {{HostAddress}}/games
Accept: application/json

###
GET {{HostAddress}}/games/1
Accept: application/json

###
POST {{HostAddress}}/games
Content-Type: application/json

{
  "name": "GTA V",
  "genreId": 2,
  "price": 25.99,
  "releaseDate": "2024-02-18"
}

###
PUT {{HostAddress}}/games/1
Content-Type: application/json

{
  "name": "Grand Theft Auto V",
  "genreId": 4,
  "price": 15.99,
  "releaseDate": "2013-09-17"
}

###
DELETE {{HostAddress}}/games/2

